# Generated by Django 5.2.4 on 2025-07-24 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
    ]
