# Generated by Django 5.2.4 on 2025-07-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_alter_company_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='standard',
            field=models.CharField(default='62443', max_length=255),
        ),
    ]
