# Generated by Django 5.2.4 on 2025-08-06 16:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_alter_company_options_remove_company_output_excel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('owner', 'company_name')},
        ),
    ]
